apiVersion: v1
kind: Service
metadata:
  name: {{ include "blog-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "blog-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}        # Service port (80)
      targetPort: {{ .Values.service.targetPort }}  # Container port (8080)
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "blog-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
