apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blog-app.fullname" . }}-config
  labels:
    {{- include "blog-app.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.global.environment | quote }}
  APP_VERSION: {{ .Chart.AppVersion | quote }}