apiVersion: v2
name: blog-app
description: Production-grade React/Firebase blog application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: redis
    version: 17.11.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled