# Global settings
global:
  appName: blog-app
  environment: dev
  region: us-east-1

# Image settings
image:
  repository: kelomo2502/blog-app-gitops
  pullPolicy: IfNotPresent
  tag: v1

# Replica settings
replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

# Resource limits
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Firebase secrets (will be overridden by env-specific values)
firebase:
  apiKey: ""
  authDomain: ""
  projectId: ""
  storageBucket: ""
  messagingSenderId: ""
  appId: ""

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 80

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Redis caching
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false