global:
  environment: prod

image:
  tag: "{{ .Values.image.tag | default .Chart.AppVersion }}"
  pullPolicy: Always

replicaCount: 3
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http.drop_invalid_header_fields.enabled=true
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:123456789012:certificate/xxxxxx"
  hosts:
    - host: blog.gbenga.online
      paths: ["/"]
  tls:
    - hosts:
        - blog.yourdomain.com
      secretName: blog-tls

firebase:
  apiKey: "PROD_API_KEY"
  authDomain: "prod-project.firebaseapp.com"